# use the official Bun image
# see all versions at https://hub.docker.com/r/oven/bun/tags
FROM docker.io/oven/bun:1 AS base
WORKDIR /usr/src/app

# install dependencies into temp directory
# this will cache them and speed up future builds
FROM base AS install
# install with dev dependencies (for tools stage)
RUN mkdir -p /temp/dev
COPY package.json bun.lock /temp/dev/
RUN cd /temp/dev && bun install --frozen-lockfile

# install with --production (exclude devDependencies)
RUN mkdir -p /temp/prod
COPY package.json bun.lock /temp/prod/
RUN cd /temp/prod && bun install --frozen-lockfile --production

# copy node_modules from temp directory
# then copy all (non-ignored) project files into the image
FROM base AS prerelease
COPY --from=install /temp/dev/node_modules node_modules
COPY . .
RUN bun run build

FROM base AS release
COPY --from=install /temp/prod/node_modules ./node_modules
COPY --from=prerelease /usr/src/app/package.json ./package.json
COPY --from=prerelease /usr/src/app/bun.lock ./bun.lock
COPY --from=prerelease /usr/src/app/drizzle.config.ts ./drizzle.config.ts
COPY --from=prerelease /usr/src/app/dist ./dist
COPY --from=prerelease /usr/src/app/tsconfig.json ./tsconfig.json



# Setup database volume and permissions
RUN mkdir -p /data \
&& chown -R bun:root /usr/src/app /data \
&& chmod -R g+rw /usr/src/app /data
VOLUME ["/data"]
ENV DB_FILE_NAME=file:/data/local.db

# Set permissions for the app directory
RUN chown -R bun:root /usr/src/app
RUN chmod -R g+w /usr/src/app

# Install sqlite3 for live database access
RUN apt-get update && apt-get install -y sqlite3 && rm -rf /var/lib/apt/lists/*

USER bun
EXPOSE 8080/tcp
CMD ["bun", "dist/server/entry.mjs"]