name: Conventional Commits

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  pr-conventional-commits:
    name: conventional-commits
    runs-on: ubuntu-latest
    steps:
      - uses: ytanikin/pr-conventional-commits@1.5.2
        with:
          task_types: '["feat","fix","docs","build","style","refactor","perf","test","ci","chore","revert"]'
          add_label: "true"
          add_scope_label: "true"
